version: '3'
services:
  todoback:
    build: ./todo-app/back-end
    restart: always
    ports:
      - 3001:3001

  todofront:
    build: ./todo-app/front-end
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - todoback
    environment:
      REACT_APP_API_HOST: todoback

  todotests:
      build: ./todo-app/tests
      depends_on:
        - todoback
        - todofront
      ports:
        - 3002:3002
      environment:
        FRONT_HOST: todofront